import Foundation

public enum SystemImage: String, CaseIterable {
  case app = "app"
  case appFill = "app.fill"
  case book = "book"
  case checkmark = "checkmark"
	case chevronLeft = "chevron.left"
  case chevronRight = "chevron.right"
  case camera = "camera"
  case circle = "circle"
  case circleFill = "circle.fill"
  case docTextMagnifyingglass = "doc.text.magnifyingglass"
  case docRichtext = "doc.richtext"
  case ellipsis = "ellipsis"
  case exclamationMarkCircle = "exclamationmark.circle"
  case handRaised = "hand.raised"
  case heartFill = "heart.fill"
  case faceid = "faceid"
  case gobackward15 = "gobackward.15"
  case goforward15 = "goforward.15"
  case infoCircle = "info.circle"
  case message = "message"
  case mic = "mic"
  case numberSquare = "number.square"
  case paperclipCircle = "paperclip.circle"
  case pauseFill = "pause.fill"
  case pencil = "pencil"
  case photo = "photo"
  case playFill = "play.fill"
  case plus = "plus"
  case rectangleOnRectangle = "rectangle.on.rectangle"
  case seal = "seal"
  case squareAndArrowUp = "square.and.arrow.up"
  case trash = "trash"
  case xmark = "xmark"
  case video = "video"
  case waveform = "waveform"
}
